=== erasmus-without-paper/ewp-registry-service/src/main/resources/jaxb-schemas/ewp-specs-api-mt-dictionaries-v0.1.0/response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/erasmus-without-paper/ewp-specs-api-mt-dictionaries/tree/stable-v1"
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-mt-dictionaries/tree/stable-v1">

    <xs:annotation>
        <xs:documentation>
            This schema is a part of the Erasmus Without Paper project. Before you start using it, make
            sure you have read the general rules described here:

            http://developers.erasmuswithoutpaper.eu/
        </xs:documentation>
    </xs:annotation>

    <xs:element name="mt-dictionaries-response">
        <xs:annotation>
            <xs:documentation>
                This describes the format of the response returned by the EWP Mobility Tool+ Dictionaries
                API.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="term" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            This represents a single term in the dictionary.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="code" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        Unambiguous code of the dictionary term.
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        Description of the dictionary term.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== erasmus-without-paper/ewp-registry-service/src/test/resources/test-files/latest-examples/ewp-specs-api-mt-dictionaries-response-example.xml
<mt-dictionaries-response
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-mt-dictionaries/tree/stable-v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
         https://github.com/erasmus-without-paper/ewp-specs-api-mt-dictionaries/tree/stable-v1
         https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-mt-dictionaries/stable-v1/response.xsd
     ">

    <!-- IMPORTANT: Please see the response.xsd file for detailed requirements and descriptions of all the elements. You 
        MUST NOT base your implementation solely on the example file. -->

    <!-- Example response for training_types dictionary -->

    <term>
        <code>J</code>
        <description>Job shadowing</description>
    </term>

    <term>
        <code>O</code>
        <description>Other</description>
    </term>

    <term>
        <code>T</code>
        <description>Training</description>
    </term>

    <term>
        <code>W</code>
        <description>Workshop</description>
    </term>

</mt-dictionaries-response>
