=== erasmus-without-paper/ewp-registry-service/src/main/resources/schemas/ewp-specs-api-mt-projects-v1.0.0/response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/erasmus-without-paper/ewp-specs-api-mt-projects/tree/stable-v1"
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-mt-projects/tree/stable-v1">

    <xs:annotation>
        <xs:documentation>
            This schema is a part of the Erasmus Without Paper project. Before you start using it, make
            sure you have read the general rules described here:

            http://developers.erasmuswithoutpaper.eu/
        </xs:documentation>
    </xs:annotation>

    <xs:element name="mt-projects-response">
        <xs:annotation>
            <xs:documentation>
                This describes the format of the response returned by the EWP Mobility Tool+ Projects API.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="project" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            This represents a single project (agreement).
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agreement-number" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        Unambiguous identifier of the project (number of agreement).
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="start-date" type="xs:date" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        Project start date.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="end-date" type="xs:date" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        Project end date.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="action-type" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        The action type for this project.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== erasmus-without-paper/ewp-registry-service/src/test/resources/test-files/latest-examples/ewp-specs-api-mt-projects-response-example.xml
<mt-projects-response
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-mt-projects/tree/stable-v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://github.com/erasmus-without-paper/ewp-specs-api-mt-projects/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-mt-projects/stable-v1/response.xsd
    ">

    <!-- IMPORTANT: Please see the response.xsd file for detailed requirements and descriptions of all the elements. You 
        MUST NOT base your implementation solely on the example file. -->

    <project>
        <agreement-number>2017-1-PL01-KA107-037079</agreement-number>
        <start-date>2017-06-01</start-date>
        <end-date>2019-07-31</end-date>
        <action-type>KA107</action-type>
    </project>

    <project>
        <agreement-number>2017-1-PL01-KA103-035979</agreement-number>
        <start-date>2017-06-01</start-date>
        <end-date>2019-07-31</end-date>
        <action-type>KA103</action-type>
    </project>

</mt-projects-response>
