=== erasmus-without-paper/ewp-registry-service/src/main/resources/schemas/ewp-specs-api-omobility-la-cnr-v1.1.0/endpoints/stats-response.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        xmlns:trm="https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/tree/stable-v2"

        targetNamespace="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/tree/stable-v1/endpoints/stats-response.xsd"
        xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/tree/stable-v1/endpoints/stats-response.xsd"
>

    <xs:import
            schemaLocation="https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-types-academic-term/stable-v2/schema.xsd"
            namespace="https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/tree/stable-v2"
    />
    <xs:annotation>
        <xs:documentation>
            This schema is a part of the Erasmus Without Paper project. Before you start
            using it, make sure you have read the general rules described here:

            http://developers.erasmuswithoutpaper.eu/
        </xs:documentation>
    </xs:annotation>

    <xs:element name="las-incoming-stats-response">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="academic-year-la-stats" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            This element represents a single academic year by which Learning Agreements are grouped.
                            It contains a list of statistics for the specified year.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="receiving-academic-year-id" type="trm:AcademicYearId">
                                <xs:annotation>
                                    <xs:documentation>
                                        The year for which statistics are specified.

                                        Note, that sending and receiving HEIs MAY use different academic year
                                        identifiers (e.g. "2010/2011" vs. "2010/2010" or "2011/2011"). This
                                        particular identifier is the year identifier at the *receiving* HEI, not the
                                        sending HEI.

                                        This means that the sending HEI MUST know how the receiving HEI identifies its
                                        academic years (i.e. whether it lies on the northern or southern hemisphere),
                                        and be able to match its mobilities with these identifiers.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-incoming-total" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-incoming-some-version-approved" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with at least one version approved by the receiving HEI.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-incoming-latest-version-approved" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with the latest version approved by the receiving HEI.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-incoming-latest-version-rejected" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with the latest version rejected by the receiving HEI.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-incoming-latest-version-awaiting" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with the latest version awaiting receiving HEIâ€™s
                                        approval.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== erasmus-without-paper/ewp-registry-service/src/test/resources/test-files/latest-examples/ewp-specs-api-omobility-la-cnr-endpoints-stats-response-example.xml
<las-incoming-stats-response
        xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/tree/stable-v1/endpoints/stats-response.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
        https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/tree/stable-v1/endpoints/stats-response.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/tree/stable-v1/endpoints/stats-response.xsd
    "
>

    <academic-year-la-stats>
        <receiving-academic-year-id>2021/2022</receiving-academic-year-id>
        <la-incoming-total>109</la-incoming-total>
        <la-incoming-some-version-approved>70</la-incoming-some-version-approved>
        <la-incoming-latest-version-approved>67</la-incoming-latest-version-approved>
        <la-incoming-latest-version-rejected>0</la-incoming-latest-version-rejected>
        <la-incoming-latest-version-awaiting>39</la-incoming-latest-version-awaiting>
    </academic-year-la-stats>

    <academic-year-la-stats>
        <receiving-academic-year-id>2022/2023</receiving-academic-year-id>
        <la-incoming-total>77</la-incoming-total>
        <la-incoming-some-version-approved>9</la-incoming-some-version-approved>
        <la-incoming-latest-version-approved>9</la-incoming-latest-version-approved>
        <la-incoming-latest-version-rejected>1</la-incoming-latest-version-rejected>
        <la-incoming-latest-version-awaiting>66</la-incoming-latest-version-awaiting>
    </academic-year-la-stats>

</las-incoming-stats-response>
